draft:
  draftFilesByYear:
    2020: Nfl_Draft_Prospects_2020.xlsx
    2019: Nfl_Draft_Prospects_2019.xlsx
    2018: Nfl_Draft_Prospects_2018.xlsx
    2017: Nfl_Draft_Prospects_2017.xlsx
  teams:
    - Arizona Cardinals
    - Atlanta Falcons
    - Baltimore Ravens
    - Buffalo Bills
    - Carolina Panthers
    - Chicago Bears
    - Cincinnati Bengals
    - Cleveland Browns
    - Dallas Cowboys
    - Denver Broncos
    - Detroit Lions
    - Green Bay Packers
    - Houston Texans
    - Indianapolis Colts
    - Jacksonville Jaguars
    - Kansas City Chiefs
    - Los Angeles Chargers
    - Los Angeles Rams
    - Las Vegas Raiders
    - Miami Dolphins
    - Minnesota Vikings
    - New England Patriots
    - New Orleans Saints
    - New York Giants
    - New York Jets
    - Oakland Raiders
    - Philadelphia Eagles
    - Pittsburgh Steelers
    - San Francisco 49ers
    - Seattle Seahawks
    - Tampa Bay Buccaneers
    - Tennessee Titans
    - Washington Redskins