server:
  port: 9595
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: AARONrodgers12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
draft:
  draftFilesByYear:
    2020: Nfl_Draft_Prospects_2020.xlsx
    2019: Nfl_Draft_Prospects_2019.xlsx
    2018: Nfl_Draft_Prospects_2018.xlsx
    2017: Nfl_Draft_Prospects_2017.xlsx
    2016: Nfl_Draft_Prospects_2016.xlsx
    2015: Nfl_Draft_Prospects_2015.xlsx
    2014: Nfl_Draft_Prospects_2014.xlsx
  positionGroupings:
    offensiveLine: 
      - OL
      - C
      - T
      - OT
      - G
      - OG
    skillPosition: 
      - QB
      - WR
      - TE
      - RB
      - FB
    defensiveBack: 
      - DB
      - CB
      - FS
      - S
      - SS
    defensiveLine: 
      - DL
      - EDGE
      - DE
      - DT
      - NT
    lineBackers: 
      - OLB
      - LB
      - ILB   
    specialTeams: 
      - LS
      - P
      - K
    all: 
      - OL
      - C
      - T
      - OT
      - G
      - OG 
      - QB
      - WR
      - TE
      - RB
      - FB 
      - DB
      - CB
      - FS
      - S
      - SS 
      - DL
      - EDGE
      - DE
      - DT
      - NT 
      - OLB
      - LB
      - ILB    
      - LS
      - P
      - K
    offense: 
      - OL
      - C
      - T
      - OT
      - G
      - OG 
      - QB
      - WR
      - TE
      - RB
      - FB 
    defense: 
      - DB
      - CB
      - FS
      - S
      - SS 
      - DL
      - EDGE
      - DE
      - DT
      - NT 
      - OLB
      - LB
      - ILB    
  draftRounds:
    - Rnd 1
    - Rnd 2
    - Rnd 3
    - Rnd 4
    - Rnd 5
    - Rnd 6
    - Rnd 7
  teams:
    - Arizona Cardinals
    - Atlanta Falcons
    - Baltimore Ravens
    - Buffalo Bills
    - Carolina Panthers
    - Chicago Bears
    - Cincinnati Bengals
    - Cleveland Browns
    - Dallas Cowboys
    - Denver Broncos
    - Detroit Lions
    - Green Bay Packers
    - Houston Texans
    - Indianapolis Colts
    - Jacksonville Jaguars
    - Kansas City Chiefs
    - Los Angeles Chargers
    - San Diego Chargers
    - Los Angeles Rams
    - St. Louis Rams
    - Las Vegas Raiders
    - Miami Dolphins
    - Minnesota Vikings
    - New England Patriots
    - New Orleans Saints
    - New York Giants
    - New York Jets
    - Oakland Raiders
    - Philadelphia Eagles
    - Pittsburgh Steelers
    - San Francisco 49ers
    - Seattle Seahawks
    - Tampa Bay Buccaneers
    - Tennessee Titans
    - Washington Redskins